# Variables
GRADLEW = ./gradlew
GRADLE_BUILD_CMD = $(GRADLEW) build
GRADLE_RUN_CMD = $(GRADLEW) run

build: clean build-only

build-only:
	$(GRADLE_BUILD_CMD)

run:
	$(GRADLE_RUN_CMD)

clean:
	$(GRADLEW) clean
